### PR TITLE
Move external-link icon after text to prevent bad wrapping

### PR DESCRIPTION
**Pull request by rhamilto**
Supports https://github.com/openshift/origin-web-console/issues/2770

attn: @petervo, @spadgett

### CODE REVIEW

**Review by martinpitt — CHANGES_REQUESTED** [review]
It feels a bit odd to have the icon after the text, and also  this does not solve the problem in principle; how about using a non-breaking space (`&nbsp;`) instead of the regular one, or using CSS (`white-space: nowrap`)?

**Comment by rhamilto** [comment]
@martinpitt, it is the standard convention on Wikipedia and other sites to put the icon after the link.  For example,

screen shot 2018-03-02 at 4 30 47 pm

This is the pattern we've adopted in the OpenShift web console.

**Comment by martinpitt** [comment]
OK, so that was not just done to prevent wrapping (the commit message is misleading then). But AFAIK the wrapping could still happen between the label and the icon, no? Wouldn't a non-breaking space between them look better?

**Comment by rhamilto** [comment]
> But AFAIK the wrapping could still happen between the label and the icon, no? Wouldn't a non-breaking space between them look better?

My assumption is that wrapping of the URL is a given, but you are correct, there are some cases where the icon could wrap independently of the URL, which a non-breaking space would solve.  I don't have a strong opinion either way.  @spadgett, do you?

**Comment by spadgett** [comment]
We've had trouble even with the non-breaking space unfortunately. We usually give the URLs `word-wrap: break-word;` so that they can break if needed, but it means that the `&nbsp;` is not honored and the icon can wrap by itself. It's been surprisingly hard problem to solve.

**Pull request closed without merging**
